# Generated by Django 5.0.3 on 2024-04-26 07:58

import Themis.models.employee
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('location', models.CharField(max_length=50, verbose_name='客户地点')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='OA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OA_name', models.CharField(max_length=50, verbose_name='运营区域')),
                ('OA_code', models.CharField(max_length=20, verbose_name='区域代码')),
            ],
            options={
                'verbose_name': '运营区域',
                'verbose_name_plural': '运营区域',
            },
        ),
        migrations.CreateModel(
            name='PositionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5, verbose_name='职级')),
                ('type', models.CharField(max_length=20, verbose_name='序列')),
            ],
            options={
                'verbose_name': '职级',
                'verbose_name_plural': '职级',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='项目节点')),
                ('_order_reserved', models.CharField(default='-1', max_length=20, verbose_name='序号')),
            ],
            options={
                'verbose_name': '项目节点',
                'verbose_name_plural': '项目节点',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目类型',
                'verbose_name_plural': '项目类型',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_departments', to='Themis.department', verbose_name='上级部门')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.oa', verbose_name='区域')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='职位')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.AddField(
            model_name='oa',
            name='OA_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.position', verbose_name='区域经理'),
        ),
        migrations.AddField(
            model_name='department',
            name='deputy_director',
            field=models.ManyToManyField(blank=True, related_name='deputy_directing_departments', to='Themis.position', verbose_name='副主管'),
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directing_departments', to='Themis.position', verbose_name='主管'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目编号')),
                ('snapshot', models.ImageField(blank=True, default='project_snapshot/default.png', null=True, upload_to='project_snapshot/', verbose_name='项目快照')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('initiation_date', models.DateField(blank=True, null=True, verbose_name='立项日期')),
                ('completion_date_est', models.DateField(blank=True, null=True, verbose_name='预计验收日期')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.oa', verbose_name='项目运营区域')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.customer', verbose_name='客户')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.projectstatus', verbose_name='项目节点')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.projecttype', verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('name', models.CharField(max_length=30, verbose_name='员工姓名')),
                ('employee_number', models.CharField(blank=True, max_length=20, verbose_name='员工工号')),
                ('date_joined', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='入职时间')),
                ('_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资')),
                ('salary_place', models.CharField(blank=True, max_length=40, null=True)),
                ('work_place', models.CharField(blank=True, max_length=40, null=True)),
                ('contract_place', models.CharField(blank=True, max_length=40, null=True)),
                ('contract_renewed_times', models.SmallIntegerField(default=0)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('insurance_place', models.CharField(blank=True, max_length=40, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('NB', 'Non-binary'), ('U', 'Prefer not to disclose')], default='U', max_length=2, verbose_name='Gender')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('expertise', models.CharField(blank=True, max_length=300, null=True, verbose_name='专长')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='头像')),
                ('phone', models.CharField(help_text='请按格式输入手机号码：‘1234567890’', max_length=17, validators=[Themis.models.employee.Employee.validate_phone_number], verbose_name='手机号码')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='id number')),
                ('id_address', models.CharField(blank=True, max_length=200, null=True)),
                ('graduated_from', models.CharField(blank=True, max_length=30, null=True)),
                ('degree', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='employee_groups', related_query_name='employee', to='auth.group', verbose_name='groups')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.position', verbose_name='职位')),
                ('position_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.positionlevel', verbose_name='职级')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='employee_permissions', related_query_name='employee', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='')),
                ('status', models.CharField(choices=[('todo', '待分配'), ('in-progress', '进行中'), ('paused', '已暂停'), ('cancelled', '已取消'), ('delayed', '已逾期'), ('completed', '已完成')], default='todo', max_length=20, verbose_name='')),
                ('priority', models.CharField(choices=[('0', '普通'), ('1', '进行中'), ('2', '已暂停'), ('3', '已取消')], default='0', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Themis.task', verbose_name='')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_tasks', to='Themis.project', verbose_name='')),
                ('DRI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('allocator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='BM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracted_projects', to=settings.AUTH_USER_MODEL, verbose_name='商务经理'),
        ),
        migrations.AddField(
            model_name='project',
            name='PM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AddField(
            model_name='project',
            name='watched_by',
            field=models.ManyToManyField(related_name='watched_projects', to=settings.AUTH_USER_MODEL, verbose_name='关注项目'),
        ),
    ]
